### ISSUE TITLE
sample_svea() should be used in SVEA

### ISSUE THREAD

**Issue by bramgrooten** [SuReLI/SGQN#1]
https://github.com/SuReLI/SGQN/blob/96ddeb9dec0740a7f96c49b6c9f956d80b90066d/DMC/src/algorithms/svea.py#L55

Why is sample_drq() used here? It should be sample_svea(), right?
(drq also augments next_obs, while svea leaves this untouched)

See also: https://github.com/nicklashansen/dmcontrol-generalization-benchmark/pull/16

**Comment by AdilZouitine** [comment]
Hey, you're right.
Why do we have `sample_drq()` instead? Because we cloned the repo of Nicklas Hansen one year ago, and the `sample_svea()` modification occurred 6 months ago (after we published SGQN)

**Comment by bramgrooten** [comment]
Ah right, thanks for your quick response. Would probably be good to adjust it in this repo as well :)
