### ISSUE TITLE
Confusion about Capacity of ReplayBuffer

### ISSUE THREAD

**Issue by RayYoh** [SuReLI/SGQN#2]
`replay_buffer = utils.ReplayBuffer(
        obs_shape=env.observation_space.shape,
        action_shape=env.action_space.shape,
        capacity=args.train_steps,
        batch_size=args.batch_size,
    )`
Hello authors, thx for your great work. 
I have one question about the capacity of the replaybuffer, is there any reasons to set the capacity by train_steps.

**Comment by DavidBert** [comment]
HI,
Thanks for your interest in SGQN.
Actually, we based most of our implementation on https://github.com/nicklashansen/dmcontrol-generalization-benchmark.
The part of code you mention directly comes from this repo.
I do not know if there was, at the time, a specific reason for this choice but the default number of steps in the experiments is 500K which seems to be a standard capacity for a replay buffer.

**Comment by RayYoh** [comment]
Hello, thanks for your kind reply. But acording to the original [DrQ](https://github.com/denisyarats/drq/blob/dd040f144ed8f696c7db35087cd80c87372edb64/train.py#L82) code, I find that they use a hyperparameter to set the cabicity and their default parameter is 100000.

**Comment by DavidBert** [comment]
Yes, that's true. But as I said, we based our implementation on the one corresponding to the [SVEA paper](https://arxiv.org/pdf/2107.00644.pdf).
For sake of fair comparison, we used the same hyperparameters for all SAC based algorithms, which were the ones described in appendix H of SVEA paper.
![image](https://github.com/SuReLI/SGQN/assets/12252506/d533fcfb-2e72-451c-a09f-fd7b973b168b)

**Comment by RayYoh** [comment]
OK. Got that, thanks for your kind reply.
