### ISSUE TITLE
 finger spin

### ISSUE THREAD

**Issue by kailugaji** [SuReLI/SGQN#5]
Hello, I am experimenting on the finger spin task in DistractingCS environment, batch size=64, the evaluation result is all 0, while on other tasks there are values, is this the reason for the batch size setting?

**Comment by DavidBert** [comment]
Hi, we did not test other batch sizes during our experiments.
We base most of our implementation on  [the original DMControl Generalization Benchmark repository](https://github.com/nicklashansen/dmcontrol-generalization-benchmark ) and took the default parameters used there.
Have you tried vanilla SAC with this batch size?

**Comment by kailugaji** [comment]
> Hi, we did not test other batch sizes during our experiments. We base most of our implementation on [the original DMControl Generalization Benchmark repository](https://github.com/nicklashansen/dmcontrol-generalization-benchmark) and took the default parameters used there. Have you tried vanilla SAC with this batch size?

Ok, thank you for your reply
